CREATE TABLE IF NOT EXISTS Pessoa (
    id SERIAL UNIQUE NOT NULL PRIMARY KEY,
    cpf VARCHAR(11) UNIQUE,
    nome VARCHAR(50) NOT NULL,
    sobrenome VARCHAR(50) NOT NULL,
	  email VARCHAR(50),
	  cidade VARCHAR(50),
	  pais VARCHAR(50)
);

CREATE TABLE IF NOT EXISTS usuarios (
    id_usuario SERIAL,
    nome VARCHAR(100) NOT NULL,
    username VARCHAR(100) NOT NULL,
    senha VARCHAR(100) NOT NULL,
    role VARCHAR(50) NOT NULL
);